# DO NOT CHANGE VERSION
version: 1.0.2
auto_update_check: true
debug: false
lang: en_US
console:
  longpluginname: true
double_shulker_chance:
  enabled: true
  rate: 50
enderman_to_shulker_chance:
  enabled: false
  rate: 75
  spawn_enderman_on_fail: true
radius_between_spawns: 10
